name: agamennone

services:
  agamennone:
    build: "."
    depends_on:
      - db
    volumes:
      - ./config.json:/app/config.json
      - ./submitters/:/app/submitters/
    command:
      [
        "--verbose",
        "--config",
        "/app/config.json",
        "--db",
        "mysql://agamennone:agamennone@tcp(db:3306)/agamennone",
      ]
    ports:
      - "${EXPOSE_HOST}:1234:1234"
    restart: on-failure

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: agamennone
      MYSQL_DATABASE: agamennone
      MYSQL_USER: agamennone
      MYSQL_PASSWORD: agamennone
    ports:
      - "${EXPOSE_HOST}:3306:3306"
    restart: on-failure
    volumes:
      - db:/var/lib/mysql

  grafana:
    image: grafana/grafana
    depends_on:
      - db
    ports:
      - "${EXPOSE_HOST}:5000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    restart: on-failure

volumes:
  db:
