{
 "title": "Flags",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "exploit",
    "label": "Exploit",
    "query": "SELECT UNIQUE(sploit) FROM flags"
   }
  ]
 },
 "panels": [
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT COUNT(flag), status FROM agamennone.flags GROUP BY status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Recieved flags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT\n  COUNT(flag) AS \"flags\",\n  $__timeGroup(received_time, $__interval) as \"time\",\n  sploit\nFROM\n  agamennone.flags\nWHERE\n  $__timeFilter(received_time)\nGROUP BY\n  sploit,\n  $__timeGroup(received_time, $__interval)\nORDER BY\n  received_time ASC"
    }
   ]
  },
  {
   "title": "Last flags",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT flag, sploit, status, team, received_time FROM agamennone.flags ORDER BY received_time DESC LIMIT 200 "
    }
   ]
  },
  {
   "title": "Accepted flags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT\n  COUNT(flag) AS \"flags\",\n  $__timeGroup(sent_time, $__interval) as \"time\",\n  sploit\nFROM\n  agamennone.flags\nWHERE\n  $__timeFilter(received_time)\n  and status = \"accepted\"\nGROUP BY\n  sploit,\n  $__timeGroup(received_time, $__interval)\nORDER BY\n  received_time ASC"
    }
   ]
  },
  {
   "title": "Rejected flags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT\n  COUNT(flag) AS \"flags\",\n  $__timeGroup(sent_time, $__interval) as \"time\",\n  sploit\nFROM\n  agamennone.flags\nWHERE\n  $__timeFilter(received_time)\n  and status = \"rejected\"\nGROUP BY\n  sploit,\n  $__timeGroup(received_time, $__interval)\nORDER BY\n  received_time ASC"
    }
   ]
  },
  { "title": "Exploit: $exploit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "exploit" },
  {
   "title": "Flags obtained",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "agamennone",
     "rawSql": "SELECT\n  COUNT(flag) AS \"flags\",\n  $__timeGroup(sent_time, $__interval) as \"time\",\n  status\nFROM\n  agamennone.flags\nWHERE\n  $__timeFilter(received_time) and\n  sploit in ($exploit)\nGROUP BY\n  status,\n  $__timeGroup(received_time, $__interval)\nORDER BY\n  received_time ASC"
    }
   ]
  }
 ]
}